const obj = {
    "success": true,
    "msg": "操作成功",
    "obj": [
      {
        "isenable": 103,
        "unit": "120",
        "indexDesc": 133,
        "indexName": "本院系师资总数",
        "trueValue": "136",
        "indexSql": "139",
        "id": 134,
        "standDesc": 100,
        "standContion": null
      },
      {
        "isenable": "11.50%",
        "unit": "13%",
        "indexDesc": "14.3%",
        "indexName": "本院系专任教师总数占专任教师总数百分比",
        "trueValue": "14.41%",
        "indexSql": "14.67%",
        "id": "13.90%",
        "standDesc": "11.49$",
        "standContion": null
      },
      {
        "isenable": 102,
        "unit": "110",
        "indexDesc": 121,
        "indexName": "本院系省级及以上教学名师总数",
        "trueValue": "126",
        "indexSql": "131",
        "id": "135",
        "standDesc": "100",
        "standContion": null
      },
      {
        "isenable": 79,
        "unit": "80",
        "indexDesc": 53,
        "indexName": "本院系省级及以上专任教学名师总数",
        "trueValue": "76",
        "indexSql": "78",
        "id": "79",
        "standDesc": 78,
        "standContion": null
      },
      {
        "isenable": 29,
        "unit": "24",
        "indexDesc": 18,
        "indexName": "本院系省级及以上兼职教学名师总数",
        "trueValue": "11",
        "indexSql": "13",
        "id": 14,
        "standDesc": 18,
        "standContion": null
      },
      {
        "isenable": 6,
        "unit": "9",
        "indexDesc": 7,
        "indexName": "本院系外籍教学名师总数",
        "trueValue": "5",
        "indexSql": "8",
        "id": 9,
        "standDesc": 5,
        "standContion": null
      },
      {
        "isenable": 6,
        "unit": "5",
        "indexDesc": 4,
        "indexName": "本院系外籍教学专任名师总数",
        "trueValue": "4",
        "indexSql": "6",
        "id": 5,
        "standDesc": 5,
        "standContion": null
      },
      {
        "isenable": 30,
        "unit": "34",
        "indexDesc": 34,
        "indexName": "本院系专业带头人教师总数",
        "trueValue": "32",
        "indexSql": "34",
        "id": 35,
        "standDesc": 30,
        "standContion": null
      },
      {
        "isenable": 29,
        "unit": "30",
        "indexDesc": 32,
        "indexName": "本院系专任中专业带头人教师总数",
        "trueValue": "29",
        "indexSql": "30",
        "id": 32,
        "standDesc": 28,
        "standContion": null
      },
      {
        "isenable": 7,
        "unit": "3",
        "indexDesc": 6,
        "indexName": "本院系兼职中专业带头人教师总数",
        "trueValue": "3",
        "indexSql": "4",
        "id": 5,
        "standDesc": 6,
        "standContion": null
      },
      {
        "isenable": 27,
        "unit": "33",
        "indexDesc": 36,
        "indexName": "本院系校级以上专业（学科）带头人教师数量",
        "trueValue": "38",
        "indexSql": "37 ",
        "id": 34,
        "standDesc": 30,
        "standContion": null
      },
      {
        "isenable": 26,
        "unit": "28",
        "indexDesc": 29,
        "indexName": "本院系专任中校级以上专业（学科）带头人教师总数",
        "trueValue": "26",
        "indexSql": "31",
        "id": 27,
        "standDesc": 24,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "4",
        "indexDesc": 3,
        "indexName": "本院系兼职中校级以上专业（学科）带头人教师总数",
        "trueValue": "4",
        "indexSql": "6",
        "id": 5,
        "standDesc": 2,
        "standContion": null
      },
      {
        "isenable": 53,
        "unit": "52",
        "indexDesc": 56,
        "indexName": "本院系骨干教师总数",
        "trueValue": "53",
        "indexSql": "58",
        "id": 54,
        "standDesc": 52,
        "standContion": null
      },
      {
        "isenable": 49,
        "unit": "53",
        "indexDesc": 55,
        "indexName": "本院系专任中骨干教师总数",
        "trueValue": "49",
        "indexSql": "56",
        "id": 55,
        "standDesc": 48,
        "standContion": null
      },
      {
        "isenable": 4,
        "unit": "6",
        "indexDesc": 7,
        "indexName": "本院系兼职中骨干教师总数",
        "trueValue": "8",
        "indexSql": "9",
        "id": 7,
        "standDesc": 5,
        "standContion": null
      },
      {
        "isenable": 48,
        "unit": "50",
        "indexDesc": 51,
        "indexName": "本院系校级以上专业（学科）骨干教师数量",
        "trueValue": "49",
        "indexSql": "53 ",
        "id": 60,
        "standDesc": 47,
        "standContion": null
      },
      {
        "isenable": 45,
        "unit": "50",
        "indexDesc": 51,
        "indexName": "本院系专任中校级以上专业（学科）骨干教师数量",
        "trueValue": "49",
        "indexSql": "51 ",
        "id": 50,
        "standDesc": 49,
        "standContion": null
      },
      {
        "isenable": 2,
        "unit": "3",
        "indexDesc": 4,
        "indexName": "本院系兼职中校级以上专业（学科）骨干教师数量",
        "trueValue": "2",
        "indexSql": "3 ",
        "id": 4,
        "standDesc": 2,
        "standContion": null
      },
      {
        "isenable": 6,
        "unit": "7",
        "indexDesc": 8,
        "indexName": "本院系专任中双型型教师总数",
        "trueValue": 7,
        "indexSql": "10",
        "id": 8,
        "standDesc": 5,
        "standContion": null
      },
      {
        "isenable": 2,
        "unit": "3",
        "indexDesc": 2,
        "indexName": "本院系兼职中双型型教师总数",
        "trueValue": 3,
        "indexSql": " 4",
        "id": 3,
        "standDesc": 2,
        "standContion": null
      },
      {
        "isenable": 89,
        "unit": "95",
        "indexDesc": 94,
        "indexName": "本院系高级职务教师总数",
        "trueValue": "89",
        "indexSql": "92 ",
        "id": 89,
        "standDesc": 88,
        "standContion": null
      },
      {
        "isenable": 80,
        "unit": "82",
        "indexDesc": 83,
        "indexName": "本院系专任教师中高级职务教师总数",
        "trueValue": "80",
        "indexSql": "84 ",
        "id": 83,
        "standDesc": 80,
        "standContion": null
      },
      {
        "isenable": 9,
        "unit": "10",
        "indexDesc": 9,
        "indexName": "本院系兼职教师中高级职务教师总数",
        "trueValue": "9",
        "indexSql": "10 ",
        "id": 8,
        "standDesc": 8,
        "standContion": null
      },
      {
        "isenable": 23,
        "unit": "24",
        "indexDesc": 23,
        "indexName": "本院系实践教学专职指导教师数量",
        "trueValue": "23",
        "indexSql": 25,
        "id": 22,
        "standDesc": 22,
        "standContion": null
      },
      {
        "isenable": 20,
        "unit": "22",
        "indexDesc": 23,
        "indexName": "本院系专任教师中实践教学专职指导教师数量",
        "trueValue": "21",
        "indexSql": 24,
        "id": 23,
        "standDesc": 19,
        "standContion": null
      },
      {
        "isenable": 3,
        "unit": "4",
        "indexDesc": 4,
        "indexName": "本院系兼职教师中实践教学专职指导教师数量",
        "trueValue": "3",
        "indexSql": 5,
        "id": 4,
        "standDesc": 3,
        "standContion": null
      },
      {
        "isenable": 15,
        "unit": "14",
        "indexDesc": 13,
        "indexName": "本院系校内实训教学专职指导教师总量",
        "trueValue": 13,
        "indexSql": 12,
        "id": 12,
        "standDesc": 13,
        "standContion": null
      },
      {
        "isenable": 36,
        "unit": "35",
        "indexDesc": 37,
        "indexName": "本院系专任教师中校内实训教学专职指导教师总量",
        "trueValue": 36,
        "indexSql": 34,
        "id": 35,
        "standDesc": 34,
        "standContion": null
      },
      {
        "isenable": 15,
        "unit": "13",
        "indexDesc": 16,
        "indexName": "本院系兼职教师中校内实训教学专职指导教师总量",
        "trueValue": 15,
        "indexSql": 16,
        "id": 14,
        "standDesc": 13,
        "standContion": null
      },
      {
        "isenable": 6,
        "unit": "4",
        "indexDesc": 3,
        "indexName": "本院系教师流失总数",
        "trueValue": "7",
        "indexSql": "6",
        "id": 5,
        "standDesc": 7,
        "standContion": null
      },
      {
        "isenable": 3,
        "unit": "2",
        "indexDesc": 3,
        "indexName": "本院系专任教师流失总数",
        "trueValue": "3",
        "indexSql": "4",
        "id": 3,
        "standDesc": 3,
        "standContion": null
      },
      {
        "isenable": 2,
        "unit": "1",
        "indexDesc": 3,
        "indexName": "本院系兼职教师流失总数",
        "trueValue": "2",
        "indexSql": "3",
        "id": 2,
        "standDesc": 2,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "0",
        "indexDesc": 1,
        "indexName": "本院系专业带头人教师流失总数",
        "trueValue": "1",
        "indexSql": "2",
        "id": 1,
        "standDesc": 0,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "2",
        "indexDesc": 1,
        "indexName": "本院系专任中专业带头人教师流失总数",
        "trueValue": "1",
        "indexSql": "2",
        "id": 1,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "0",
        "indexDesc": 1,
        "indexName": "本院系兼职中专业带头人教师流失总数",
        "trueValue": "1",
        "indexSql": "0",
        "id": 1,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "2",
        "indexDesc": 2,
        "indexName": "本院系骨干教师流失总数",
        "trueValue": "2",
        "indexSql": "1",
        "id": 1,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "0",
        "indexDesc": 0,
        "indexName": "本院系专任中骨干教师流失总数",
        "trueValue": "1",
        "indexSql": "1",
        "id": 1,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "1",
        "indexDesc": 0,
        "indexName": "本院系兼职中骨干教师流失总数",
        "trueValue": "1",
        "indexSql": "0",
        "id": 1,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 2,
        "unit": "1",
        "indexDesc": 2,
        "indexName": "本院系外籍教师流失总数",
        "trueValue": "3",
        "indexSql": "2",
        "id": 2,
        "standDesc": 2,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "2",
        "indexDesc": 1,
        "indexName": "本院系专任中外籍教师流失总数",
        "trueValue": "1",
        "indexSql": "2",
        "id": 1,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "1",
        "indexDesc": 2,
        "indexName": "本院系兼职中外籍教师流失总数",
        "trueValue": "2",
        "indexSql": "2",
        "id": 1,
        "standDesc": 2,
        "standContion": null
      },
      {
        "isenable": 10,
        "unit": "12",
        "indexDesc": 9,
        "indexName": "本院系实践教学专职指导教师总数",
        "trueValue": 13,
        "indexSql": 12,
        "id": 11,
        "standDesc": 9,
        "standContion": null
      },
      {
        "isenable": 10,
        "unit": "9",
        "indexDesc": 8,
        "indexName": "本院系专任中实践教学专职指导教师总数",
        "trueValue": 7,
        "indexSql": 9,
        "id": 8,
        "standDesc": 9,
        "standContion": null
      },
      {
        "isenable": 386,
        "unit": "386",
        "indexDesc": 387,
        "indexName": "本院系招生总数",
        "trueValue": "386",
        "indexSql": 390,
        "id": 434,
        "standDesc": 387,
        "standContion": null
      },
      {
        "isenable": "99.89%",
        "unit": "99.92%",
        "indexDesc": "99.10%",
        "indexName": "本院系新生报到率",
        "trueValue": "99.39%",
        "indexSql": "99.46%",
        "id": "99.37%",
        "standDesc": "99.10%",
        "standContion": null
      },
      {
        "isenable": "5.03%",
        "unit": "5.12%",
        "indexDesc": "5.45%",
        "indexName": "本院系特长生率",
        "trueValue": "5.03%",
        "indexSql": "5.49%",
        "id": "5.41%",
        "standDesc": "4.98%",
        "standContion": null
      },
      {
        "isenable": 1536,
        "unit": "1555",
        "indexDesc": 1496,
        "indexName": "本院系在校生数量",
        "trueValue": "1395",
        "indexSql": "1496",
        "id": 1310,
        "standDesc": 1400,
        "standContion": null
      },
      {
        "isenable": '19.7%',
        "unit": '17.6%',
        "indexDesc": '17.8%',
        "indexName": "本院系党员学生率",
        "trueValue": "19.6%",
        "indexSql": "18.3%",
        "id": '17.9%',
        "standDesc": "18.9",
        "standContion": null
      },
      {
        "isenable": 0.2,
        "unit": 0.16,
        "indexDesc": 0.19,
        "indexName": "本院系辍学学生比例",
        "trueValue": 0.17,
        "indexSql": 0.18,
        "id": 0.17,
        "standDesc": 0.19,
        "standContion": null
      },
      {
        "isenable": 20.3,
        "unit": 18.7,
        "indexDesc": 17.9,
        "indexName": "本院系缺课率",
        "trueValue": 17.98,
        "indexSql": 17.4,
        "id": 17.1,
        "standDesc": 18.3,
        "standContion": null
      },
      {
        "isenable": 10,
        "unit": "12",
        "indexDesc": 11,
        "indexName": "本院系培训项目数量",
        "trueValue": 12,
        "indexSql": 11,
        "id": 475,
        "standDesc": 8,
        "standContion": null
      },
      {
        "isenable": 92.3,
        "unit": 94,
        "indexDesc": 93.5,
        "indexName": "本院系毕业生达标率",
        "trueValue": 94.1,
        "indexSql": 93.8,
        "id": 93.0,
        "standDesc": 92.1,
        "standContion": null
      },
      {
        "isenable": 37,
        "unit": "35",
        "indexDesc": 32,
        "indexName": "本院系省级以上获奖教师总量",
        "trueValue": "37",
        "indexSql": "36",
        "id": 35,
        "standDesc": 34,
        "standContion": null
      },
      {
        "isenable": 35,
        "unit": "36",
        "indexDesc": 35,
        "indexName": "本院系省级以上获奖专任教师总量",
        "trueValue": "35",
        "indexSql": "36",
        "id": 35,
        "standDesc": 36,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "1",
        "indexDesc": 2,
        "indexName": "本院系省级以上获奖兼职教师总量",
        "trueValue": "2",
        "indexSql": "3",
        "id": 4,
        "standDesc": 1,
        "standContion": null
      },
      {
        "isenable": 68,
        "unit": "67",
        "indexDesc": 57,
        "indexName": "本院系 地市级以上获奖教师总量",
        "trueValue": "68",
        "indexSql": "57",
        "id": 55,
        "standDesc": 55,
        "standContion": null
      },
      {
        "isenable": 62,
        "unit": "61",
        "indexDesc": 59,
        "indexName": "本院系地市级以上获奖专任教师总量",
        "trueValue": "63",
        "indexSql": "62",
        "id": 59,
        "standDesc": 61,
        "standContion": null
      },
      {
        "isenable": 4,
        "unit": "5",
        "indexDesc": 5,
        "indexName": "本院系地市级以上获奖兼职教师总量",
        "trueValue": "5",
        "indexSql": "6",
        "id": 5,
        "standDesc": 3,
        "standContion": null
      },
      {
        "isenable": 32,
        "unit": "33",
        "indexDesc": 35,
        "indexName": "本院系获技术专利奖的教师总量",
        "trueValue": "32",
        "indexSql": "34",
        "id": 33,
        "standDesc": 31,
        "standContion": null
      },
      {
        "isenable": 29,
        "unit": "30",
        "indexDesc": 28,
        "indexName": "本院系获技术专利奖的专任教师总量",
        "trueValue": "29",
        "indexSql": "29",
        "id": 27,
        "standDesc": 27,
        "standContion": null
      },
      {
        "isenable": 1,
        "unit": "1",
        "indexDesc": 3,
        "indexName": "本院系获技术专利奖的兼职教师总量",
        "trueValue": "2",
        "indexSql": "3",
        "id": 530,
        "standDesc": 1,
        "standContion": null
      }
    ],  
    "obj2": [{
      'indexName': "师生比",
      'isenable': 15.25,
      'indexSql': 15.43,
      'indexDesc': 15.48,
      'unit': 14.26,
      'id': 15.29,
      'trueValue': 18.00,
      'standDesc': 16.23
    },
    {
      'indexName': "具有研究生学位教师占专任教师的比例",
      'isenable': 63.81,
      'indexSql': 57.66,
      'indexDesc': 52.38,
      'unit': 39.16,
      'id': 48.90,
      'trueValue': 15.00,
      'standDesc': 50.30
    },
    {
      'indexName': "生均教学行政用房(平方米/生)",
      'isenable': 17.31,
      'indexSql': 17.68,
      'indexDesc': 18.89,
      'unit': 18.86,
      'id': 18.20,
      'trueValue': 16.00,
      'standDesc': 17.24
    },
    {
      'indexName': "生均科研仪器设备值(元/生)",
      'isenable': 12870.91,
      'indexSql': 9950.71,
      'indexDesc': 10247.61,
      'unit': 13088.26,
      'id': 9288.80,
      'trueValue': 4000.00,
      'standDesc': 1012.23
    },
    {
      'indexName': "生均图书(册/生)",
      'isenable': 74.26,
      'indexSql': 75.04,
      'indexDesc': 69.78,
      'unit': 76.03,
      'id': 80.01,
      'trueValue': 60.00,
      'standDesc': 66.40
    },
    {
      'indexName': "具有高级职务教师占专任教师的比例(%)",
      'isenable': 34.93,
      'indexSql': 31.86,
      'indexDesc': 30.31,
      'unit': 33.80,
      'id': 28.70,
      'trueValue': 20.00,
      'standDesc': 30.23
    },
    {
      'indexName': "生均占地面积(平方米/生)",
      'isenable': 62.51,
      'indexSql': 63.84,
      'indexDesc': 65.67,
      'unit': 70.95,
      'id': 68.00,
      'trueValue': 59.00,
      'standDesc': 66.23
    },
    {
      'indexName': "生均宿舍面积(平方米/生)",
      'isenable': 8.05,
      'indexSql': 7.91,
      'indexDesc': 8.51,
      'unit': 7.77,
      'id': 8.64,
      'trueValue': 6.50,
      'standDesc': 7.03
    },
    {
      'indexName': "生均实践场所(平方米/生)",
      'isenable': 8.49,
      'indexSql': 8.50,
      'indexDesc': 8.90,
      'unit': 8.68,
      'id': 8.35,
      'trueValue': 8.30,
      'standDesc': 7.91
    },
    {
      'indexName': "百名学生配教学用计算机数(台)",
      'isenable': 32.56,
      'indexSql': 26.68,
      "indexDesc": 27.74,
      "unit": 27.23,
      "id": 25.54,
      "trueValue": 10.00,
      "standDesc": 26.34
    },
    {
      "indexName": "新增科研仪器设备所占比例(%)",
      "isenable": 11.97,
      "indexSql": 11.31,
      "indexDesc": 11.29,
      "unit": 12.32,
      "id": 11.55,
      "trueValue": 10.00,
      "standDesc": 10.23
    },
    {
      "indexName": "生均年进书量(册)",
      "isenable": 2.87,
      "indexSql": 3.01,
      "indexDesc": 2.53,
      "unit": 2.75,
      "id": 3.10,
      "trueValue": 2.00,
      "standDesc": 2.07
    },

        {
          "isenable": "1557",
          "unit": "1560",
          "indexDesc": "1590",
          "indexName": "全校师资总量",
          "trueValue": "1557",
          "indexSql": "1598",
          "id": "1557",
          "standDesc": "1550",
          "standContion": null
        },
        {
          "isenable": "845",
          "unit": "855",
          "indexDesc": "865",
          "indexName": "全校专任师资总量",
          "trueValue": "845",
          "indexSql": "855",
          "id": "847",
          "standDesc": "840",
          "standContion": null
        },
        {
          "isenable": "53",
          "unit": "52",
          "indexDesc": 54,
          "indexName": "全校兼职师资队伍数量",
          "trueValue": "53",
          "indexSql": "55",
          "id": 52,
          "standDesc": 53,
          "standContion": null
        },
        {
          "isenable": "32",
          "unit": "33",
          "indexDesc": "32",
          "indexName": "全校外籍教师数量",
          "trueValue": "34",
          "indexSql": "35",
          "id": 35,
          "standDesc": "30",
          "standContion": null
        },
        {
          "isenable": "25",
          "unit": "26",
          "indexDesc": "27",
          "indexName": "全校外籍教师中专任师资数量",
          "trueValue": "25",
          "indexSql": "24",
          "id": "25",
          "standDesc": "23",
          "standContion": null
        },
        {
          "isenable": "207",
          "unit": "209",
          "indexDesc": "206",
          "indexName": "全校专业带头人师资数量",
          "trueValue": "207",
          "indexSql": "272",
          "id": "205",
          "standDesc": "205",
          "standContion": null
        },
        {
          "isenable": "153",
          "unit": "154",
          "indexDesc": "159",
          "indexName": "全校骨干教师师资数量",
          "trueValue": "156",
          "indexSql": "164",
          "id": "154",
          "standDesc": "152",
          "standContion": null
        },
        {
          "isenable": 0.4,
          "unit": 0.1,
          "indexDesc": 0.11,
          "indexName": "全校专业师生比",
          "trueValue": "0.1",
          "indexSql": 0.12,
          "id": 0.12,
          "standDesc": "0.15",
          "standContion": null
        },
        {
          "isenable": "207",
          "unit": "208",
          "indexDesc": "210",
          "indexName": "全校专业带头人师资数量",
          "trueValue": "217",
          "indexSql": "214",
          "id": 217,
          "standDesc": 206,
          "standContion": null
        },
        {
          "isenable": 131,
          "unit": "134",
          "indexDesc": 134,
          "indexName": "全校省级以上获奖教师总量",
          "trueValue": "131",
          "indexSql": "130",
          "id": 138,
          "standDesc": 121,
          "standContion": null
        },
        {
          "isenable": "0.01%",
          "unit": "0.01%",
          "indexDesc": "0.021%",
          "indexName": "全校辍学学生比例",
          "trueValue": "0.012%",
          "indexSql": "0.01%",
          "id": "0.011%",
          "standDesc": "0.013%",
          "standContion": null
        },
        {
          "isenable": "89.06%",
          "unit": "89.26%",
          "indexDesc": "89.12%",
          "indexName": "年度教育部审核的全校体质健康测试达标率",
          "trueValue": "89.06%",
          "indexSql": "89.36%",
          "id": "89.26%",
          "standDesc": "89.03%",
          "standContion": null
        },
        {
          "isenable": "54.27%",
          "unit": "54.37%",
          "indexDesc": "54.41%",
          "indexName": "专任师资队伍总量占全校师资总量的百分比",
          "trueValue": "54.27%",
          "indexSql": "54.47%",
          "id": "54.30%",
          "standDesc": "54.20%",
          "standContion": null
        },
        {
          "isenable": "13.29%",
          "unit": "13.29%",
          "indexDesc": "13.19%",
          "indexName": "全校专业带头人占教师总量的百分比",
          "trueValue": "13.39%",
          "indexSql": "13.30%",
          "id": "13.48%",
          "standDesc": "13.11%",
          "standContion": null
        },
        {
          "isenable": "9.82%",
          "unit": "9.16%",
          "indexDesc": "9.34%",
          "indexName": "全校骨干教师占教师总量的百分比",
          "trueValue": "9.22%",
          "indexSql": "9.92%",
          "id": "9.82%",
          "standDesc": "9.72%",
          "standContion": null
        },
        {
          "isenable": "23",       
          "unit": "24",
          "indexDesc": "21",       "indexName": "学校重点专业数量",       "trueValue": "23",       "indexSql": "28",
          "id": "26",       "standDesc": "20",
          "standContion": null
        },
        {
          "isenable": "27.45%",
          "unit": "27.45%",
          "indexDesc": "27.25%",
          "indexName": "学校重点专业比例",
          "trueValue": "27.41%",
          "indexSql": "27.45%",
          "id": "27.23%",
          "standDesc": "27.15%",
          "standContion": null
        },
        {
          "isenable": "8",
          "unit": "9",
          "indexDesc": "8",
          "indexName": "学校特色专业数量",
          "trueValue": "10",
          "indexSql": "12",
          "id": "11",
          "standDesc": "7",
          "standContion": null
        },
        {
          "isenable": "11.01%",
          "unit": "11.22%",
          "indexDesc": "11.21%",
          "indexName": "学校特色专业比例",
          "trueValue": "11.41%",
          "indexSql": "11.51%",
          "id": "11.01%",
          "standDesc": "10.01%",
          "standContion": null
        }
      ],
    "data": null
  }

  export default obj

